### ISSUE TITLE
New student - After creating new, we get popup of "Google smart lock" (see attached screen)

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#178]

**Comment by eran1205** [comment]
[Uploading Screen Shot 2018-08-14 at 10.26.24.png...]

**Comment by doronbali** [comment]
This can be done, in some browsers, with a hack.
Anyway since we are not setting the current user password perhapse it is better to remoce this field and move to default passwordvwhich will be automatically created or a an autogenerated password which willbhave to be modified at first login

**Comment by ulmanA** [comment]
@leoraperry 
The solutions I found for disable the browser's password manager for the code weren't work. 
Those solutions are very hacky and the the browser's latest versions prevent all of them.
There is one solution that might work but it has security issue
(https://stackoverflow.com/a/32836440/3983953)
and even if it working now it can be also blocked by the browsers' on next version.

**Comment by leoraperry** [comment]
@ulmanA I don't have a technical resolution, but it doesn't make sense to suggest the user saving a password for creating a new user (that is not me). I'm sure we developed here at the site dozens of portals that allow creating users - do all of them suggest the admin user to save the new user's password?? No way...
What triggers this smart lock dialog? the password field? something else? 
On any case, this is a very annoying bug that can't be closed without a fix. @eran1205  please advise.

**Comment by KfirMor** [comment]
I decided to close this issue. We cannot override the browsers behavior here
