### ISSUE TITLE
Explore infra/platform options

### ISSUE THREAD

**Issue by niv1** [myspecialway/my-special-way-portal#212]
Investigate different options for infrastructure/platform and orchestration options

Example for infrastructure can be - Azure, AWS etc.

Example for platform - cloud specific components such as Serverless (web app) and other SaaS options

Example for orchestration- Kubernetes, Swarm, none (if using SaaS)

Consider the following factors:
- Application requirements - environment, db, persistency etc.
- High availability
- Scaling
- Simple CI/CD
- Costs

**Comment by eran1205** [comment]
Hi Niv,

As Danny mentioned today at your meeting, we need a very quick solution to the bad situation that the server of the portal is in now. 
Yesterday I worked on the portal and from 10 calls to the server, 7 of them failed.
As you know, we have DEMO on Thursday to אhe Municipality of Tel Aviv and we need FAST solution. After it, we can think about changing the server and etc.

Can we have short term solution the the server of the portal?

**Comment by niv1** [comment]
Hi Eran,
Right, I am aware of the Thursday's demo requirements, though, this issue is not related to that but to the long-term solution.
We can open separate issue for the current problem or continue in Slack, to decide how to handle it, for example, I can think of few possible tracks, like- reproduce and fix the current problem or deploy new temporary environment just for the demo...
