### ISSUE TITLE
student schedule e2e tests (see description)

### ISSUE THREAD

**Issue by dimkinv** [myspecialway/my-special-way-portal#235]
* should display relevant schedule
    * should open popup on click on cell
    * should update existing cell
    * should create lesson+location on empty cell
    * should be able to discard changes inside popup
    * principle
        * should be able to update class name and grade

child of #228

**Comment by mr372e** [comment]
should be able to update class name and grade -> this is incorrect. The principle should be able to update class name and grade from the CLASS schedule page, and not from the student schedule page.
