### ISSUE TITLE
Class schedule page - Changes to the schedule are not saved

### ISSUE THREAD

**Issue by mr372e** [myspecialway/my-special-way-portal#264]
Step 1 - Log in as principle
Step 2 - go to the class managment page
Step 3 - Select a class to edit
Step 4 - From the schedule, select a cell and edit it
After closing the pop-up, no data is changed in the schedule table, and no data is save to the DB. Also, no errors are shown in the console.

**Comment by tulitheprogrammer** [comment]
Is in PR stage on server side
