### ISSUE TITLE
חסרה ולידציה על ססמא

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#334]
child of #329

**Comment by ulmanA** [comment]
@eran1205  
איזה ולידציה אנחנו רוצים בסיסמא?

**Comment by eran1205** [comment]
Invalid password - password must be at least 8 characters longs - both letters and digits. If invalid, show the message:
הססמא צריכה להכיל לפחות 8 תווים, כולל אותיות ומספרים.
