### ISSUE TITLE
לאחר שמירה של משתמש קופץ דיאלוג save password  של google  ללא הצדקה

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#338]
child of #329

**Comment by ofirmgr** [comment]
לא הצלחתי לשחזר את הבאג. לפחות בכרום לא קפץ לי שום דיאלוג

**Comment by ulmanA** [comment]
@leoraperry @eran1205 
https://github.com/myspecialway/my-special-way-portal/issues/178
