### ISSUE TITLE
תלמיד חדש מתווסף לרשימת התלמידים במיקום לא ברור - צריך להתווסף בסדר אלפאבתי עולה (לפי שם פרטי ומשפחה)

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#340]
child of #329

**Comment by pabloli** [comment]
Fixed in branch , UT remaining (2hr)

**Comment by ulmanA** [comment]
@pabloli 
Pull request: #404 
already marged and fixed that issue
Sorry that I didn't saw that was one issue for students and another for users

**Comment by ulmanA** [comment]
Pull request: #404

**Comment by pabloli** [comment]
NP
