### ISSUE TITLE
מערכת השעות לא פעילה עד שאין שם ושכבה

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#348]
חסרה הודעת שגיאה "שכבה הינו שדה חובה" כאשר מנסים להוסיף משהו למערכת ולא ניתן כי לא הוגדרה שכבה
ההודעה לשם כיתה חסר מופיעה חתוכה - ההודעה צריכה להופיע מתחת לשדה ולא בתוכו, כפי שמוגדר בשאר המערכת

**Comment by taltal115** [comment]
Done in #348-empty-class-name-message
