### ISSUE TITLE
אין ולידציה על מחיקת כיתה שמקושרים אליה תלמידים

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#350]

**Comment by eylonmalin** [comment]
What we shell do with the existing students ?
Is there ability to move the students to another class ?

**Comment by eran1205** [comment]
You can't delete a class that students are related. Please see what we done in case that try to delete teacher that  connected to class with students

**Comment by Noamalon** [comment]
What about this bug? @eylonmalin did you fix it?

**Comment by eylonmalin** [comment]
no

**Comment by Noamalon** [comment]
Can't reproduce... someone already fixed it
I get proper message on class deletion with students
