### ISSUE TITLE
טקסט הודעת שגיאה למחיקת תלמיד - לא לפי ההגדרות

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#351]

**Comment by eylonmalin** [comment]
What is the requirement ?
Which text should be displayed ?
Is there are doc with the requirements ?

**Comment by eran1205** [comment]
see issue #39 (User screens - Finalize UI & Validations)

**Comment by doritrieur** [comment]
@eran1205  
did you refer to delete student from students' management? because on this page it seems like already done.

on delete users page the dialog is different (seems like not formatted).

**Comment by doritrieur** [comment]
@eran1205  seems like the current implementation matches spec.
