### ISSUE TITLE
עדכון שיעורים וסמלים - רשימה סופית

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-portal#382]
*****NOTE*****
4 Symbols were added:
 חדר קטן חיצוני
חדק בעלי חיים קטן 
חדר בעלי חיים גדול
חדר הבעה ויצירה

Final list of classes and symbols can be found in the ppt along with mapping to all image files.
Please seed in DB.

Final PPT:
https://tspace.web.att.com/files/app/file/00f4f9ff-3c47-442c-aedb-46a687043f17

Final Symbols Resources:
https://tspace.web.att.com/files/app#/folder/620b3cd1-1257-4794-a5cf-d1a1a46257f9

needs #454
needs #455

**Comment by doronbali** [comment]
@leoraperry, @pelegbahar 
unable to open the link - tried several times

**Comment by doronbali** [comment]
@leoraperry , we need to match pre-defined lessons to actual icons.
here is a list of all predefined lessons, we need each lesson to hold the icon name:
[
    {
      "title": "אומנות",
      "icon": "art"
    },
    {
      "title": "אנגלית",
      "icon": "english"
    },
    {
      "title": "אנגלית מוסיקלית",
      "icon": "musical english"
    },
    {
      "title": "ארוחת ארבע",
      "icon": "afternoon"
    },
    {
      "title": "ארוחת בוקר",
      "icon": "breakfest"
    },
    {
      "title": "ארוחת צהריים",
      "icon": "lunch-icon"
    },
    {
      "title": "בריכה",
      "icon": "pool"
    },
    {
      "title": "ג'ימבורי",
      "icon": "gimbori"
    },
    {
      "title": "הבעה ביצירה",
      "icon": "expression"
    },
    {
      "title": "הכנה לחיים",
      "icon": "reality"
    },
    {
      "title": "העסקה עצמית",
      "icon": "self-occupation"
    },
    {
      "title": "הפסקה",
      "icon": "break-icon"
    },
    {
      "title": "הצגה",
      "icon": "show"
    },
    {
      "title": "הקלדה",
      "icon": "Typing"
    },
    {
      "title": "זהירות בדרכים",
      "icon": "traffic"
    },
    {
      "title": "חגים",
      "icon": "Holidays"
    },
    {
      "title": "חווה",
      "icon": "farm"
    },
    {
      "title": "חינוך",
      "icon": "education"
    },
    {
      "title": "חקלאות",
      "icon": "agriculture garden"
    },
    {
      "title": "חשבון",
      "icon": "math"
    },
    {
      "title": "טיול",
      "icon": "trip"
    },
    {
      "title": "טיפול",
      "icon": "therapy"
    },
    {
      "title": "טקס",
      "icon": "ceremony"
    },
    {
      "title": "יום הולדת",
      "icon": "birthday"
    },
    {
      "title": "כלכלת בית",
      "icon": "economy"
    },
    {
      "title": "כתיבה",
      "icon": "writing"
    },
    {
      "title": "למידה",
      "icon": "learning"
    },
    {
      "title": "מדעים",
      "icon": "science"
    },
    {
      "title": "מוטוריקה",
      "icon": "motor skills"
    },
    {
      "title": "מולדת",
      "icon": "moledet"
    },
    {
      "title": "מוסיקה",
      "icon": "music"
    },
    {
      "title": "מלאכה",
      "icon": "crafts"
    },
    {
      "title": "מפגש בוקר",
      "icon": "morning"
    },
    {
      "title": "מפגש צהריים",
      "icon": "noon"
    },
    {
      "title": "מקהלה",
      "icon": "choir"
    },
    {
      "title": "משחק חברתי",
      "icon": "sociail-game"
    },
    {
      "title": "משחק חופשי",
      "icon": "free-game"
    },
    {
      "title": "נבחרת ספורט",
      "icon": "sport-team"
    },
    {
      "title": "ניקיון אישי ",
      "icon": "cleaning"
    },
    {
      "title": "סנוזלן",
      "icon": "snoozelen"
    },
    {
      "title": "ספורט",
      "icon": "sport"
    },
    {
      "title": "ספרות",
      "icon": "literature"
    },
    {
      "title": "ספריה",
      "icon": "library"
    },
    {
      "title": "עונות השנה",
      "icon": "seasons"
    },
    {
      "title": "פיזור תלמידים",
      "icon": "dismiss-icon"
    },
    {
      "title": "קבלת שבת",
      "icon": "shabat"
    },
    {
      "title": "קבלת תלמידים",
      "icon": "no-icon"
    },
    {
      "title": "קפוארה",
      "icon": "kapuera"
    },
    {
      "title": "קריאה",
      "icon": "reading"
    },
    {
      "title": "רובוטיקה",
      "icon": "robotics"
    },
    {
      "title": "ריפוי בעיסוק",
      "icon": "occupational-therapy"
    },
    {
      "title": "ריתמוסיקה",
      "icon": "ritmusic"
    },
    {
      "title": "שיחת סיכום יום",
      "icon": "daily"
    },
    {
      "title": "שילוב",
      "icon": "shiluv"
    },
    {
      "title": "שינוי",
      "icon": "change"
    },
    {
      "title": "שיעור נושא",
      "icon": "subject"
    },
    {
      "title": "שעת סיפור",
      "icon": "story"
    },
    {
      "title": "תורה",
      "icon": "tora"
    },
    {
      "title": "תנועה",
      "icon": "movement"
    },
    {
      "title": "תקשוב",
      "icon": "ict"
    },
    {
      "title": "תקשורת",
      "icon": "communication"
    }
  ]

CC @pelegbahar

**Comment by doronbali** [comment]
@leoraperry, 
can you export the (lesson-icon) list from pttx file? maybe we can use this as the predefined lesson list.
why are there 2 icons for each lesson?

**Comment by pelegbahar** [comment]
@doronbali I have changed the images name according to the above.
Please find the new files here:
https://tspace.web.att.com/files/app/file/ae5fe8c1-57da-4d98-bdba-fa8224ee6255

@leoraperry please assist:
הפסקה אין. יש הפסקת בוקר והפסקת צהריים
לא מצאתי:
הבעה ביצירה
חינוך
פיזור תלמידים
קבלת תלמידים
שעת סיפור
