### ISSUE TITLE
User screens - Finalize UI &  Validations

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-portal#39]
Finalize UI according to SG for

Users List screen
User popup

Upon creating/updating a user, handle the following validation:

Not all fields are filled-in - if one of the fields is not filled-in (no spaces), show the relevant message beside the field (according to SG):
. שם שדה> הינו שדה חובה>

Invalid user name - user name should be in English, at least 5 characters (no spaces). for example: michals.
If invalid, show the message:
שם משתמש חייב להיות לפחות חמישה תווים באנגלית.

User name already exists - If username is already taken by another user, show the message:
שם משתמש כבר קיים. אנא נסה שם משתמש אחר.

Invalid password - password must be at least 8 characters longs - both letters and digits. If invalid, show the message:
הססמא צריכה להכיל לפחות 8 תווים, כולל אותיות ומספרים.

Invalid email address-  If email is invalid, show the message:
כתובת אמייל לא חוקית. אנא נסה שנית.

The field "סוג משתמש" is a dropdown list with 2 values: 
מנהל מערכת
מורה

The field כיתה will be enabled only in case user type is "Teacher" and should  include all classes defined in DB (class management).
Actual classes names:
כיתת פטל
כיתת סחלב
כיתת דקל
כיתת תמר
כיתת ניצן
כיתת נרקיס
כיתת שקד
כיתת תאנה
כיתת סברס
כיתת הדר
כיתת ברוש
כיתת גפן
כיתת רימון

Upon clicking delete button, show a confirmation message:
?<האם אתה בטוח שברצונך למחוק את המשתמש <שם משתמש
אשר - will remove the user
בטל - will close the dialog. User will not be removed.

Parent of #58
Parent of #84
Parent of #85
Parent of #179
Parent of #180
Parent of #181
Parent of #182
Parent of #183
Parent of #184
Parent of #185
Parent of #186
Parent of #187
Parent of #189
Parent of #190
Parent of #188

**Comment by eran1205** [comment]
need #58

**Comment by eran1205** [comment]
need #58
