### ISSUE TITLE
Delete class dialog - grade does not displayed

### ISSUE THREAD

**Issue by doritrieur** [myspecialway/my-special-way-portal#425]
Delete class dialog - grade details does not displayed on the delete class dialog

+ replace "delete" to מחק

**Comment by doritrieur** [comment]
![deleteClass.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b5581d5b5b1dd00157ec2c2/125516c66e82c728ace21e0d46ec91962696868a83e8ac50e611b2843b492d762a10e17132d0e178ea462e00560d4fac10505b44fcf8db28f5b73b23d84e17ff933c0120996048e6edc00db513bb27814e80b2bf8848c4e83f27ef888d5d73.PNG)

**Comment by michalheim32** [comment]
Fix verify 27/01
