### ISSUE TITLE
Classes screens - Finalize UI & Validations

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-portal#46]
Finalize UI according to SG for

Classed List screen
Class Info

Upon creating/updating a class (clicking Save button), handle the following validations:

When exiting the screen (browser back, back to "All Classes", select another option from menu, browser to another page...) perform mandatory fields validation:
Missing class name/class type:
. שם שדה> הינו שדה חובה>

Upon exiting class name field/exiting page validate:
Invalid class name - class name should be in Hebrew and unique. for example: פטל.
שם כיתה חייב להיות בעברית.
שם כיתה קיים. אנא בחר שם כיתה אחר.

The field "שכבה" is a dropdown list with the folloiwng values:
א
ב
ג
ד
ה
ו

The class schedule will be handle on a separate US

Upon clicking delete button on classes list screen:
Check if class is already associated with students. If true, show an error message:
לא ניתן למחוק את הכיתה כיוון שיש תלמידים המשוייכים אליה.
אישור
Otherwise,  show a confirmation message:
?<האם אתה בטוח שברצונך למחוק את כיתה <שם כיתה
אשר - will remove the class
בטל - will close the dialog. Class will not be removed.

In case

need #78
need #79
need #80
need #82
need #83
need #142

**Comment by eran1205** [comment]
need #78
need #79
need #80
