### ISSUE TITLE
Web portal - Logout - after logout we get login page, but with error in F12 console

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#464]
Press on logged user name in left upper corner, press "Continue" in pop-up. we get login page, but with error 401 in F12 Network and in console error: rror: Network error: Http failure response for https://msw-westus-app-k8s.att.io:3000/graphql: 401 Unauthorized

**Comment by michalheim32** [comment]
Fix verify 27/01
