### ISSUE TITLE
Web portal - Update user details - get errors in F12 console

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#466]
Principle selete "Manage users" option. Press on any user in list - user details pop-up is opened. In F12 console see errors for every detail field - see scrren capture "F12 console when open user details". Error example: "ERROR TypeError: Cannot assign to read only property 'firstname' of object '[object Object]' "

**Comment by mr372e** [comment]
Could not reproduce (18/12/2018 14:44)

**Comment by lanalazar** [comment]
8-Jan - the same problem
![F12 console when open user details - 08-Jan.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfbafaa18b7ec0011210913/125516c66e82c728ace21e0d46cec5c863818ca79ce6b346e44af891270628632c0ae33e6380f168bb476f0006030dbc5c485f4ce183d875b4aa2e30c80351b882294d7ed43843acbdd61aee08e8218b1e8db2bc8a4d92eb6e24e0d8dd5d220c4749d7ab0268f9d31e8a4afc59e04a5fa5163265ef75357f4f9716702e792a.png)

**Comment by michalheim32** [comment]
Fix verify 27/01
