### ISSUE TITLE
Web site not support browser IE11

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#481]
Console - 

SCRIPT5022: Exception thrown and not caught
File: polyfills.88d216d57c22f769af44.js, Line: 1, Column: 48913

**Comment by eran1205** [comment]
@leoraperry 
Hi Leorra, is it in our scope?

**Comment by leoraperry** [comment]
@eran1205  Chrome browser is top priority. Let's focus on that.
