### ISSUE TITLE
Create new User - Email first login url

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#488]
http://localhost:4200/first-login/aoxf3uulf6b

Need to be 

https://msw-westus-app-k8s.att.io/first-login/aoxf3uulf6b

**Comment by okelman** [comment]
Now user redirect to the site but get empty screen at the upper left user see : "שלום NULL NULL"

https://msw-westus-app-k8s.att.io//first-login/r45d5g1eqdq
![bug.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46ea819d61cec1b99de6b546a749b2ce6b1325237c00f62a2987b278be1a2f515f5e1caf12595817aeeb9539e4e76224d50152a7842f4d7ed43c19a6b9871bba03ba258d4e82bfbb8f5e8d.png)

**Comment by michalheim32** [comment]
Fix verify 27/01
