### ISSUE TITLE
Create new User - Email first login url

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#493]
Now user redirect to the site but get empty screen at the upper left user see : "שלום NULL NULL"

https://msw-westus-app-k8s.att.io//first-login/r45d5g1eqdq

**Comment by okelman** [comment]
![bug.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46ea819d61cec1b99de6b546a749b2ce6b1325237c00f62a2987b278be1a2f515f5e1caf12595817aeeb9539e4e76224d50152a7842f4d7ed43c16a6b9871bba03ba288c4782b3bc885e8d.png)

**Comment by okelman** [comment]
https://msw-westus-app-k8s.att.io//first-login/r45d5g1eqdq
need to be
https://msw-westus-app-k8s.att.io/first-login/r45d5g1eqdq
![bug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46ea819d61cec1b99de6b546a749b2ce6b1325237c00f62a2987b278be1a2f515f5e1caf12595817aeeb9539e4e76224d50152a7842f4d7ed43c16a6b9871bba03b324834a85b0ba8e5e8d.PNG)

**Comment by michalheim32** [comment]
Not fix duplicate with 506
