### ISSUE TITLE
Web portal - Is possible to create for student the same equal reminders (the same day + same hour)

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#500]
Teacher / principle open reminer and define day and hour. Is possible to create the same equal reminders (the same day + same hour)

**Comment by mr372e** [comment]
This might be needed, as a student might have more than one reminder for the same time (take 2 kinds of pills etc....). Will consult @leoraperry

**Comment by mr372e** [comment]
After talking with @leoraperry  - this is not a bug
