### ISSUE TITLE
Web portal - maps - When set location "disabled" in floor N it's impossible to select any other floow from drop down list

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#501]
When set location "disabled" in floor N it's impossible to select any other floow from drop down list

**Comment by lanalazar** [comment]
Error in F12 console: ERROR TypeError: Cannot read property 'filter' of undefined

**Comment by mr372e** [comment]
This bug depends on pull request #367 and needs to be rechecked once that pull request has been merged.
