### ISSUE TITLE
Web portal - New user get email and press on link

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#506]
New user received email in his account. Press on link inside email to define password - get page (URL https://msw-westus-app-k8s.att.io/first-login/2x145h925ej) with message "נראה שאירעה תקלה... אנא נסה שנית". Error in F12 console: "Fetch API cannot load https://mail.google.com/mail/u/0/?pli=1&sw=2. Redirect failed.".

**Comment by michalheim32** [comment]
Still  open also new defect 643

**Comment by michalheim32** [comment]
Not fixed 27/01
![שיחזור סיסמא2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d465f5d2dda35741e795e4af46c1d47559ebf90b29efa14db22c7af6aaf50740b0a0c0abe4b4a5a16fcfcdd2ef7bf6e718a0d03e9d16d5e26c56e10abebd00da313f871d51bdaebe5c01982fa3737e683854e3b1a0d1e89ff5835a19d4ecb4abb.PNG)
