### ISSUE TITLE
Managed Maps - Text cut off

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#511]

**Comment by okelman** [comment]
![bug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46ea819d61cec1b99de6b546a749b2ce6b1325237c00f62a2987b278be1a2f515f5e1caf12595817aeeb9539e4e76224d50152a7842f4d7ed43c18a6b9871bba04bd22894684bfbb8b5e8d.PNG)

**Comment by michalheim32** [comment]
Fix verify 27/01
