### ISSUE TITLE
Web portal - after add new student Google pop-up "Save password" appears

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#569]
After add new student Google pop-up "Save password" appears. According to Leora Perry:	אין להציג את מסך שמירת ססמא של גוגל לאחר יצירת תלמיד

**Comment by eran1205** [comment]
If someone will get to this bug, please look at https://stackoverflow.com/questions/32369/disable-browser-save-password-functionality/37292424#37292424

**Comment by lanalazar** [comment]
Sorry, bug 178 is opened

**Comment by KfirMor** [comment]
Duplicate of #178
