### ISSUE TITLE
Build Validator util

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#57]

**Comment by dkhnn** [comment]
Do we need a util with this at hand:

https://material.angular.io/components/input/examples

import {Component} from '@angular/core';
import {FormControl, Validators} from '@angular/forms';

/**
 * @title Input with error messages
 */
@Component({
  selector: 'input-errors-example',
  templateUrl: 'input-errors-example.html',
  styleUrls: ['input-errors-example.css'],
})
export class InputErrorsExample {
  emailFormControl = new FormControl('', [
    Validators.required,
    Validators.email,
  ]);
}
