### ISSUE TITLE
Web portal - Settings - Is possible to define code 1, 2, 3 digits

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#570]
Settings - Is possible to define  teacher code 1, 2, 3 digits with response 200 OK

**Comment by eran1205** [comment]
@lanalazar I tried to reproduce without success. If I try to enter less than 4 digit, it gives me "נא הקש 4 ספרות"

**Comment by lanalazar** [comment]
Try to edit exits teacher code - I can set 5 and more digits without error - see attached

![Settings (teacher code) - 6 digits.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfbafaa18b7ec0011210913/125516c66e82c728ace21e0d46db918e378b8dae9ca9f757a15cf39c2c5467702600a66230c8a37eff467206061b0dbe5d4a1f06a3a3dc78e2a436628f0e0be885680e7d943c11fdb0861fbf00e823d84e82e5ee9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc5ef242e4495da01a3e60f43b.png)
![Settings (teacher code) - 2 digits.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfbafaa18b7ec0011210913/125516c66e82c728ace21e0d46db918e378b8dae9ca9f757a15cf39c2c5467702600a66230c8a37aff467206061b0dbe5d4a1f06a3a3dc78e2a436628f0e0be885680e7d943c11fdb0861fbf00e823d84e82e5ee9850d2aa6c7bb3d4d216744b470a83ed5f34aa984ecc5ef242e4495da01a3e60f43b.png)

**Comment by eran1205** [comment]
@lanalazar yesterday we switched to other env. You need to enter mswppr.tel-aviv.gov.il

**Comment by lanalazar** [comment]
08-Jen - the same problem in new env.
