### ISSUE TITLE
Web portal - Maps - Navigation points in every floor

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#575]
As I see, every floor map has its special points (D1 - Dn, A1 - An, etc.). When I add navigation point for floor 1, I can define point of floor 2. Is it correct?

**Comment by eran1205** [comment]
@leoraperry Is it a bug?

**Comment by leoraperry** [comment]
@eran1205  I don't understand the bug

**Comment by eran1205** [comment]
@lanalazar ????

**Comment by leoraperry** [comment]
US #421 defines the seeding of the basic maps information. US #367 defines all the rules for manual definition of navigation points via maps ניהול מפה, including stating that it is the user's responsibility to define the points correctly based on the maps images. These are not interactive maps therefore we can't make such validations.

**Comment by KfirMor** [comment]
WAD
