### ISSUE TITLE
There is no option to add Additional hours for selected days

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#580]

**Comment by okelman** [comment]
please see Pictures and US
[Uploading Bug.PNG...]

**Comment by okelman** [comment]
![Bug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46ca819d61cec1b99de6b546a749b2ce6b1325237c00f62a2987b278be1a2f515f5e1caf12595817aeeb9539e4e76224d50152a7842f4d7ed43c16a6b9871bb904ba258c4683b2bb895e8d.PNG)

**Comment by celine666** [comment]
I dont see it is reproducible. maybe fixed by my previous pr. please check again

**Comment by michalheim32** [comment]
Fixed 12/02
