### ISSUE TITLE
Remainders - User able to update remainder without adding day or hour

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#583]

**Comment by okelman** [comment]
when saving user get in console error and reminder no saved
![Bug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46ca819d61cec1b99de6b546a749b2ce6b1325237c00f62a2987b278be1a2f515f5e1caf12595817aeeb9539e4e76224d50152a7842f4d7ed43c16a6b9871bb904ba268e4784b1ba8a5e8d.PNG)

**Comment by michalheim32** [comment]
Fix verified 28/01
