### ISSUE TITLE
Add lesson - no error message if not select icon

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#594]
According to Leora:
במידה ולא בוחרים סמל, אין הודעת שגיאה. כפתור עדכן לא מגיב.

**Comment by shimbarks** [comment]
What is the expected behaviour?
Should the button be initially grey and become purple only after name and symbol are chosen?
(this is the behaviour when adding a student or a map)

**Comment by KfirMor** [comment]
@shimbarks Yes please, this should be the behaviour

**Comment by michalheim32** [comment]
20/02 verified
