### ISSUE TITLE
No limit of data string length in field

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-portal#605]
No limit of data string length in lesson name 
 field, cause visibility problems

**Comment by michalheim32** [comment]
![DataStringlength.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d46cc958e22b197bb86e7b84fa153f78021046b313916ac217586f76ae5002e035f5a1aa910510d45fca8812fa6b63d22890f0aea823f4d68d47f40f2ecdd42e64bef62994597b4bc804dc5ec3b2de2888a483617031c9bb2.png)
in practice:
![DataStringlength2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d46cc958e22b197bb86e7b84fa153f7802114653f6b14b1247a80e03cfd1839540d5f4bf844095616fdf9d823a2b63c71d85f58ecd63e0d66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3923ef8e8c4a361b00188fed10.png)

**Comment by eran1205** [comment]
@leoraperry Hi Leora, what is the max length of lesson name?

**Comment by leoraperry** [comment]
I would give it a limit of 30 chars.
