### ISSUE TITLE
Links not working in case Students name too long

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-portal#611]
ניהול תלמידים -->> No limit of data string length in Students name field, cause links not working and ,visibility problems
see attached file

**Comment by michalheim32** [comment]
![DataStringlength2long.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d46cc958e22b197bb86e7b84fa153f78021142b7c2703e1673295f127b54778154d555ca913585a10f9a88079a7b66d788e5c0bec836e0c75c16e43bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8b49371d051a88fa5532a88b06.png)

**Comment by eran1205** [comment]
@leoraperry Hi Leora, what is the max length of  student name?

**Comment by leoraperry** [comment]
I would limit first name to 15 and last name to 15, assuming it fits the UI both on the list and the student details screen.
