### ISSUE TITLE
First time login via email - Error 404

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#620]

**Comment by okelman** [comment]
שלום אוהד קלמן

אנו מברכים על הצטרפותך למערכת בדרכי שלי - בית הספר יחדיו.‏

שם המשתמש שלך: אוהדק

על מנת להתחיל להשתמש במערכת, יש ללחוץ על הלינק הבא ולהגדיר את סיסמתך:‏

בדרכי שלי

תודה שהצטרפת!‏

https://urldefense.proofpoint.com/v2/url?u=http-3A__mswppr.tel-2Daviv.gov.il_first-2Dlogin_k8c3gjnc7ih&d=DwMFaQ&c=LFYZ-o9_HUMeMTSQicvjIg&r=IDqlqfXTZgMBaPRPyKaXkuPRP2EeEXCLE1ilqRFMkz8&m=B3sOavbPTMQt0R5B4NPSLlbY3KPOCjvaJF4OIXBIbnk&s=kU-Lv50XmONjmO2jXapRB8PJYvlIp5kd3DF44h4FS-o&e=


http://mswppr.tel-aviv.gov.il/first-login/k8c3gjnc7ih

{"statusCode":404,"error":"Not Found","message":"Cannot GET /first-login/k8c3gjnc7ih"}

**Comment by michalheim32** [comment]
Verified 20/02
