### ISSUE TITLE
Add / edit lesson - lessons list has unnecessary space

### ISSUE THREAD

**Issue by lanalazar** [myspecialway/my-special-way-portal#623]
Add_edit lesson - in lessons list there is unnecessary space - see attached

**Comment by lanalazar** [comment]
![Add_edit lesson - in lessons list there is unnecessary space.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bfbafaa18b7ec0011210913/125516c66e82c728ace21e0d46c9909e1c8787a09ba9b346b74eff9a690b677a2744af2e6396ec26ac0277081c1b5ee8190d1d11eca0ca3be3e86225d90948ae802f1664857d40ffed9003ad41f87fd11ad6f2ae805ec5ba3d20b38ede466c1f054981fb5d35a1cb489b59f118b35f49b651673db2296b250dc15c6726796621a1fdda52808561adba152751c9e3f6b7.png)

**Comment by KfirMor** [comment]
WAD
