### ISSUE TITLE
Web portal - Settings - Missing Navigation to arrive student option

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#627]

**Comment by okelman** [comment]
![Bug.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c18a3d4eb69450013021e2d/125516c66e82c728ace21e0d46ca819d61cec1b99de6b546a749b2ce6b1325237c00f62a2987b278be1a2f515f5e1caf12595817aeeb9539e4e76224d50152a7842f4d7ed43c16a6b9871bb801b826824f81b5b8885e8d.PNG)

**Comment by eran1205** [comment]
@okelman, @leoraperry Due to the US, we don't need to implement this.

**Comment by leoraperry** [comment]
@okelman @eran1205 
As defined in the US, the only setting that should be supported is the teacher code.
Please do not use Zeplin as source of requirement. Requirements are defined in Waffle (inc. texts, features etc.). Zeplin is for SG only.
