### ISSUE TITLE
Login window-->Forgot password->Illegal Email accepted

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-portal#629]

**Comment by michalheim32** [comment]
![שכחתי ססמה.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d465f5d2dd835741e455e4603139c47559eb890876b48e13b628ae92dbc56395b4d5a1cac440c5a15f5ab882bf7be38708a5d59ee826c5827942f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e38c8f4c3a1e0d1c88f85b27ed.PNG)

**Comment by michalheim32** [comment]
אם האמייל לא חוקי, הצג את ההודעה:
כתובת אמייל לא חוקית. אנא נסה שנית

**Comment by KfirMor** [comment]
Duplicate of #625
