### ISSUE TITLE
Manage lessons

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-portal#63]
Admin users should have the option "ניהול שיעורים", which allows managing all classes names and symbols.
The user add/edit/delete a class.
When  creating a new class - user should define class name and select a symbol form the available symbols (which are not already taken by another class).
The list of available symbols should also include a default symbol, in case none of the symbols fits the class. The default symbol should always be available.
The following validations will be performed when saving the class:
Not all fields are set - 
if class name is not set (no spaces), show the message:
אנא הזן שם שדה
If symbol was not selected, show the message:
אנא בחר סמל 

Once a symbol was selected already it will not be available for selection for other class, unless the class is deleted.

When updating an existing class - the current symbol should be displayed at the top right.

When hovering over a class row, a Delete button should be displayed. Clicking it should prompt the user with the message:
כותרת: מחיקת שיעור
?<האם אתה בטוח שברצונך למחוק את שיעור <שם שיעור
בטל - will close the dialog. Class will not be removed.
אשר - check if class is not already associated to a class/student schedule. 
If class is not associated with a current schedule, delete it.
If class is associated with a current schedule, show the error message:
כותרת: מחיקת שיעור
לא ניתן למחוק את השיעור.  <שם שיעור> מקושר למערכת השעות של  <שם כיתה/שם תלמיד>
אישור - closes the dialog

https://app.zeplin.io/project/5b0d6871045bfaa54886722a/screen/5b1fcd2fce9f5b387054766f

need #132
need #133
need #134
need #135
need #136
need #137

**Comment by doronbali** [comment]
@leoraperry , canvyou provide the available icons?
Whats the flow when trying to delete a lesson that currently used by other entities?

**Comment by leoraperry** [comment]
@doronbali  icons are still in work. For now, use a temporary default icon. There are some temp icons on DB. You can ask @eran1205  or @dimkinv 
For second question - see US

**Comment by doronbali** [comment]
10x
