### ISSUE TITLE
No consistency display in add new Lesson / class

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-portal#630]
The display  of add new class does not looks like add new Lesson.
Need to add the "כפתור "הוסף

**Comment by michalheim32** [comment]
The display of add new class does not looks like add new Lesson.
Need to add the Apply or  save button

**Comment by eran1205** [comment]
@michalheim32 Add new class isn't popup. What do you mean?

**Comment by michalheim32** [comment]
@eran1205 I have test it again now and it seems OK but  when I first tested this screen it did not return the  "כיתת  XYZ  בהצלחה נוצרה"
I"ll close this defect

**Comment by michalheim32** [comment]
@eran1205 I dont have permission to close can you  close it?
