### ISSUE TITLE
Android - New scheduler changes are not syncing to the client

### ISSUE THREAD

**Issue by okelman** [myspecialway/my-special-way-portal#646]

**Comment by michalheim32** [comment]
On real time scheduler changes  syncing   the client gets error
see attached files 
![syncing to the client1_בדרכי שלי.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d46fb8d94208b8daecffdb003b055f5d42a4a2e762710f214c77454db088accfab8f65e4bd8bff3a355eb9539e6f4632adf0f4fffdb7f5a26c63845a9e98b4dbe01eb288f4f85b7ee891fc1ef6e77f5979d0d6f405147d4a61760e28b41da59f141e04851a3143767e675307446930c38.jpg)
![syncing to the client2_בדרכי שלי.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d46fb8d94208b8daecffdb003b055f5d42a4a2e762710f114c77454db088accfab8f65e4bd8bff3a355eb9539e6f4632adf0f4fffdb7f5a26c63845a9e98b4dbe01eb288f4f85b7ee891fc1ef6e77f5979d0d6f405147d4a61760e28b41da59f041e04851a3143767e672307e46940c38.jpg)

**Comment by michalheim32** [comment]
Not fixed see defect 664
