### ISSUE TITLE
Android - changes in user details /scheduler

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-portal#650]
Cause application to stuck

**Comment by michalheim32** [comment]
![Device maintenance.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d46cc918c2a8186e982e8b64db058fe95274522316546b3397f8fe62bab0021435a0d4ea9155d0e4daef8897aaeb23c708b0e08bed06a0c26d42103eee9dc4be05ce36ade0d97bcae8b44cae93821e08c8e493c19011b80fa4f78.jpg)

**Comment by pelegbahar** [comment]
@michalheim32 @ab973q not sure I understand. If there is an issue, please write a proper description, logs, flow etc.

**Comment by okelman** [comment]
Hey,
When a principle changes a student scheduler it`s sending event to the Student android client but failing to perform that change and popup`s a toast says: "בדרכי שלי עצר"

**Comment by pelegbahar** [comment]
@okelman please open Android related issues in the Android board.
