### ISSUE TITLE
Schedule that appears on the portal is not updated on mobile at all

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-portal#664]

**Comment by ab973q** [comment]
Getting  null hours from the server 

          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,
          "hours": null,

{
  "data": {
    "student": {
      "reminders": [
        {
          "enabled": true,
          "type": "MEDICINE",
          "schedule": [
            
          ]
        },
        {
          "enabled": true,
          "type": "REHAB",
          "schedule": [
            
          ]
        }
      ],
      "schedule": [
        {
          "index": "5_3",
          "hours": null,
          "lesson": {
            "title": "העסקה עצמית",
            "icon": "self-occupation"
          },
          "location": {
            "name": "חדר חיצוני קטן",
            "location_id": null,
            "position": {
              "floor": 0
            }
          }
        },
        {
          "index": "1_3",
          "hours": null,
          "lesson": {
            "title": "אנגלית",
            "icon": "00596"
          },
          "location": {
            "name": "כיתת ברוש",
            "location_id": null,
            "position": {
              "floor": 2
            }
          }
        },
        {
          "index": "6_3",
          "hours": null,
          "lesson": {
            "title": "הבעה ביצירה",
            "icon": "expression"
          },
          "location": {
            "name": "חדר הבעה ביצירה",
            "location_id": null,
            "position": {
              "floor": -1
            }
          }
        },
        {
          "index": "10_3",
          "hours": null,
          "lesson": {
            "title": "הקלדה",
            "icon": "Typing"
          },
          "location": {
            "name": "חדר סנוזלן",
            "location_id": null,
            "position": {
              "floor": 2
            }
          }
        },
        {
          "index": "11_3",
          "hours": null,
          "lesson": {
            "title": "זהירות בדרכים",
            "icon": "traffic"
          },
          "location": {
            "name": "חצר לימודית",
            "location_id": null,
            "position": {
              "floor": 0
            }
          }
        },
        {
          "index": "12_3",
          "hours": null,
          "lesson": {
            "title": "טיפול",
            "icon": "therapy"
          },
          "location": {
            "name": "חדר קלינאיות תקשורת",
            "location_id": null,
            "position": {
              "floor": -1
            }
          }
        },
        {
          "index": "13_3",
          "hours": null,
          "lesson": {
            "title": "ג'ימבורי",
            "icon": "gimbori"
          },
          "location": {
            "name": "חדר חיצוני קטן",
            "location_id": null,
            "position": {
              "floor": 0
            }
          }
        },
        {
          "index": "1_0",
          "hours": null,
          "lesson": {
            "title": "אומנות",
            "icon": "art"
          },
          "location": {
            "name": "חדר אומנות",
            "location_id": null,
            "position": {
              "floor": -1
            }
          }
        },
        {
          "index": "2_0",
          "hours": null,
          "lesson": {
            "title": "הבעה ביצירה",
            "icon": "expression"
          },
          "location": {
            "name": "חדר הבעה ביצירה",
            "location_id": null,
            "position": {
              "floor": -1
            }
          }
        },
        {
          "index": "10_0",
          "hours": null,
          "lesson": {
            "title": "העסקה עצמית",
            "icon": "self-occupation"
          },
          "location": {
            "name": "חדר היועצת",
            "location_id": null,
            "position": {
              "floor": 1
            }
          }
        },
        {
          "index": "11_0",
          "hours": null,
          "lesson": {
            "title": "ג'ימבורי",
            "icon": "gimbori"
          },
          "location": {
            "name": "חצר לימודית",
            "location_id": null,
            "position": {
              "floor": 0
            }
          }
        },
        {
          "index": "12_0",
          "hours": null,
          "lesson": {
            "title": "הקלדה",
            "icon": "Typing"
          },
          "location": {
            "name": "חדר סנוזלן",
            "location_id": null,
            "position": {
              "floor": 2
            }
          }
        },
        {
          "index": "13_0",
          "hours": null,
          "lesson": {
            "title": "הכנה לחיים",
            "icon": "reality"
          },
          "location": {
            "name": "חדר היועצת",
            "location_id": null,
            "position": {
              "floor": 1
            }
          }
        },
        {
          "index": "6_1",
          "hours": null,
          "lesson": {
            "title": "אומנות",
            "icon": "art"
          },
          "location": {
            "name": "חדר אומנות",
            "location_id": null,
            "position": {
              "floor": -1
            }
          }
        },
        {
          "index": "12_1",
          "hours": null,
          "lesson": {
            "title": "אנגלית",
            "icon": "00596"
          },
          "location": {
            "name": "חדר סנוזלן",
            "location_id": null,
            "position": {
              "floor": 2
            }
          }
        },
        {
          "index": "5_4",
          "hours": null,
          "lesson": {
            "title": "זהירות בדרכים",
            "icon": "traffic"
          },
          "location": {
            "name": "חדר סנוזלן",
            "location_id": null,
            "position": {
              "floor": 2
            }
          }
        },
        {
          "index": "6_4",
          "hours": null,
          "lesson": {
            "title": "הצגה",
            "icon": "show"
          },
          "location": {
            "name": "חצר חדשה",
            "location_id": null,
            "position": {
              "floor": 0
            }
          }
        },
        {
          "index": "11_4",
          "hours": null,
          "lesson": {
            "title": "אומנות",
            "icon": "art"
          },
          "location": {
            "name": "חדר אומנות",
            "location_id": null,
            "position": {
              "floor": -1
            }
          }
        },
        {
          "index": "1_2",
          "hours": null,
          "lesson": {
            "title": "הכנה לחיים",
            "icon": "reality"
          },
          "location": {
            "name": "חדר הכנה לחיים",
            "location_id": null,
            "position": {
              "floor": -1
            }
          }
        },
        {
          "index": "2_2",
          "hours": null,
          "lesson": {
            "title": "אנגלית מוסיקלית",
            "icon": "musical english"
          },
          "location": {
            "name": "חדר מוסיקה",
            "location_id": null,
            "position": {
              "floor": 2
            }
          }
        },
        {
          "index": "5_2",
          "hours": null,
          "lesson": {
            "title": "הבעה ביצירה",
            "icon": "expression"
          },
          "location": {
            "name": "חדר אומנות",
            "location_id": null,
            "position": {
              "floor": -1
            }
          }
        },
        {
          "index": "6_2",
          "hours": null,
          "lesson": {
            "title": "ג'ימבורי",
            "icon": "gimbori"
          },
          "location": {
            "name": "חצר לימודית",
            "location_id": null,
            "position": {
              "floor": 0
            }
          }
        },
