### ISSUE TITLE
Currently it is possible to delete a Class although it is associated to student

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-portal#665]
According to US:
Upon clicking delete button on classes list screen
Check if class is already associated with students. If true, show an error message:
לא ניתן למחוק את הכיתה כיוון שיש תלמידים המשוייכים אליה.
אישור

**Comment by michalheim32** [comment]
התוצאה לאחר מחיקה היא:
![מחיקתכיתהעםתלמידים.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d465f6a2dd4357a1e485e75f45fea0923e3f1d3c4ebb35e9cba321f9f41f582b6fcb8e74bec4a4356bcbbd671f3e57862804e0ebfd1680b71973443adb8d317bb01ba21d94cd6b7bbd91ed2f42f67b6d5db1063474f4dcbed5727a19141c95df242e44e57a414336be4752431.PNG)

**Comment by michalheim32** [comment]
![מחיקתכיתהעםתלמידים2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d465f6a2dd4357a1e485e75f45fea0923e3f1d3c4ebb35e9cba321f9f41f582b6fcb8e74bec5a4d58eeb9cb74fce36f34985619e8836d5a20c36c18feb9824eb705ba208a1d86e5bd8d1f92fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe84856a6153e6aef70376e0a.PNG)

**Comment by ab973q** [comment]
Still not fix  - The  class is deleted from classroom list  with no error but it is  visible in  student  list  see attached

![מחיקתכיתהעםתלמידים3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bdf08a4100dd00013be6b36/125516c66e82c728ace21e0d465f6a2dd4357a1e485e75f45fea0923e3f1d3c4ebb35e9cba321f9f41f582b6fcb8e74bec5b4d58eeb9cb74fce36f34985619e8836d5a20c36c18feb9824eb705ba208a1d86e5bd8d1f92fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe84450ad1b3367ef72356e0a.PNG)

**Comment by dkhnn** [comment]
@michalheim32 can you take a look please?

**Comment by michalheim32** [comment]
Verify 19/03
On deletion on refreshing the page, a message appears stating that a class to which students are associated can not be deleted
