### ISSUE TITLE
מסך תזכורות

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-portal#67]
[מסך תזכורות.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae80ca603d1cb001202249b/125516c66e82c728ace21e0d465f6a2de23579e9382308b513a647619e8e90869ecee1673295f127b54778154d555ca913585a10f9a88079a7b66d788e5c0bec836e0c75c16e43bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8c473e1d011b8cf65e33a48b06.docx)

parent of #194

require by #373 - client side
require by https://github.com/myspecialway/my-special-way-server/issues/119 - server side

**Comment by taltal115** [comment]
require by #373 - client side
require by #374 - server side
