### ISSUE TITLE
Non active hours no validation for time issues

### ISSUE THREAD

**Issue by michalheim32** [myspecialway/my-special-way-portal#672]
Non active hours  - create record for different date (from > till) - error  09:00-08:00 Accepted
                              09:00-09:00 Accepted

**Comment by KfirMor** [comment]
@michalheim32 I could not reproduce these two scenarios, need your help with that

**Comment by michalheim32** [comment]
@KfirMor see the screen shot
![זמני_אי_פעילות.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c32e747498f050011f0b03a/125516c66e82c728ace21e0d465f622ddd35431e76d608b313a4cf23edf1e5c4d0b35f9c8532296af3006b1300051bff054a5556f9ab892ef2b36d79d85d0bbcd9695f74c76f12ffb9854ced13a632c91edbe2e3d7158abd7f37ed998e47341f001d89f95935a99f48ce5ef459ac.PNG)

**Comment by KfirMor** [comment]
@michalheim32 I suspect it's old data in the database, I couldn't reproduce it after adding some fixes. Can you reproduce it? Thx, Kfir
![672.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae981cddba7f1001216d80b/125516c66e82c728ace21e0d46bec3c861cec1b99de6b546a749b2ce6b1325237c00f62a2987b278be1a2f515f5e1caf12595817aeeb9539e4e76224d50152a7842f4d7ed43c19a6b9871abf07b2218f4681b2b58a5e8d.png)

**Comment by michalheim32** [comment]
Yup Will close is !!! 21/02
