### ISSUE TITLE
Portal Login

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-portal#7]
Upon entering the portal URL for the first time, show login screen (pending UI)
Allow user to enter UN/PW.
If authentication successful, show Students screen.
Otherwise, show an error message on login screen - 
If UN/PW are incorrect show the message:  
שם משתמש/ססמא לא נכונים. אנא נסה שנית.
For any other error show the message:
נכשל בכניסה למערכת. אנא נסה שנית.

If the user checked the "זכור אותי" checkbox, he will be logged in automatically next time. Otherwise, login page will be displayed.

**Comment by dkhnn** [comment]
https://www.microcopy.co.il/single-post/password-hebrew
