### ISSUE TITLE
Student screens - Finalize UI &  Validations

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-portal#8]
Finalize UI according to SG for

Students List screen
Student personal info>

Upon creating/updating a student, handle the following validation:
1) Not all fields are filled-in - if one of the fields is not filled-in (no spaces), show the relevant message beside the field (according to SG):
. שם שדה> הינו שדה חובה>

2) Invalid user name -  user name should be in Hebrew, at least  5 characters (no spaces). for example: יניבג.
If invalid, show the message: 
שם משתמש חייב להיות לפחות חמישה תווים בעברית.

3) User name already exists - If username is already taken by another user, show the message:
שם משתמש כבר קיים. אנא נסה שם משתמש אחר.

4) Invalid password - password must be at least 8 characters longs - both letters and digits. If invalid, show the message:
הססמא צריכה להכיל לפחות 8 תווים, כולל אותיות ומספרים.

5) Boy/Girl toggle and the image at the top should be on Boy by default. Upon changing the toggle to girl, update the illustration at the top  to girl as well.

Upon Saving details, remain on the personal details screen and show a saving (שומר...) indication on the Save button, followed by a Saved indication (נשמרV -see UI ). The button indication will remain as long as the user is on the  personal details page and does not make additional updates - upon making an update on any personal details field, button should return to default (שמור).
If Save failed, show an error:
השמירה נכשלה. אנא נסה שנית.

Upon clicking delete button, show a confirmation message:
?<האם אתה בטוח שברצונך למחוק את התלמיד <שם התלמיד
אשר - will remove the student
בטל - will close the dialog. Student will not be removed.

need #178
need #170
need #169

**Comment by eran1205** [comment]
need #57
