### ISSUE TITLE
Add validation on Delete class dialog

### ISSUE THREAD

**Issue by eran1205** [myspecialway/my-special-way-portal#83]

**Comment by dkhnn** [comment]
@eran1205 what does this mean?
there is a confirmation dialogue... what validation is required?

**Comment by eran1205** [comment]
@dkhnn 
Upon clicking delete button on classes list screen, show a confirmation message:
?<האם אתה בטוח שברצונך למחוק את כיתה <שם כיתה
אשר - will remove the class
בטל - will close the dialog. Class will not be removed.
