### ISSUE TITLE
שינוי קבוע/זמני במערכת השעות

### ISSUE THREAD

**Issue by leoraperry** [myspecialway/my-special-way-portal#88]
[שינוי קבוע או זמני במערכת השעות.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae80ca603d1cb001202249b/125516c66e82c728ace21e0d465f5d2dda35431e7a5e4603139a47659eb390b169b3539c85c554de08bcccc1b8f65e4be0bff1a36e1e11cc0d51a6606df8ec7436ffb8d121a703b0aac25de05bef73cf5d8fa4b9d84cc5bc3874eed98e4f6f16011889fe0f36f3984c9b0ae457f30f04fa47693ebf3c633e559e0c742b616623a8fed753868367a4b8122b4485.docx)

**Comment by pabloli** [comment]
אם זה שינוי זמני המערכת אמורה להחזיר אותו לבד לערך הקודם. איך זה יקרה? יש Scheduler?

**Comment by leoraperry** [comment]
@pabloli השינוי חזרה אמור להתבצע אוטומטית בתום בתקופה שהוגדרה (כולל דווח לקליינט). את אופן המימוש אשאיר לך :-)

**Comment by pabloli** [comment]
@leoraperry ,
יש כמה קצוות לא ברורים.
1. איך מציגים את השינוי הזמני. על הלוח?
2. יהיה ניתן לשנות בחזרה לפני הזמן? באופן ידני כמובן.
3. מה יקרה אם יהיה שינוי זמני לאחר שינוי זמני? חוזרים למקורי,נכון?
זה בינתיים ;)

**Comment by pabloli** [comment]
התחלתי את זה אבל בגלל זמינות לא אוכל לסיים. אשמח לשתף את הקוד.
